name: Update Commit Timestamps

on:
  push:
    branches:
      - main

jobs:
  update-timestamps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get commit timestamp
      run: |
        timestamp=$(git log -1 --pretty=format:%cI)
        export COMMIT_TIME=$(git show -s --format=%ci dd28288f)
        echo "Commit timestamp: $COMMIT_TIME"
