name: Update README with file list

on:
  push:
    branches:
      - main # 또는 원하는 브랜치 이름

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        uses: jakejarvis/gh-actions-readme@v3.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          readme_path: README.md
          sections: |
            ## File List
            ${{ steps.filelist.outputs.list }}

      - name: Get file list
        id: filelist
        run: |
          echo "File list" > files.txt
          find . -type f -printf "- %p %TY-%Tm-%Td %TH:%TM\n" | sed 's/\.\///' >> files.txt
          echo "::set-output name=list::$(cat files.txt)"
